version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.1
    env_file:
      - ./.env
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  bot:
    container_name: xaosbot_debug
    image: xaosbot_debug
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
    - ./.env
    build:
      context: ../go-bot
      dockerfile: Dockerfile.debug
    ports:
      - $XAOSBOT_PORT:$XAOSBOT_PORT
      - 40000:40000
    # command: --security-opt="apparmor=unconfined" --cap-add=SYS_PTRACE


volumes:
  postgres: null
