version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.1
    env_file:
      - ./.env
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  bot:
    container_name: xaosbot
    image: xaosbot
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
    - ./.env
    build:
      context: ../go-bot
      dockerfile: Dockerfile
    ports:
      - $XAOSBOT_PORT:$XAOSBOT_PORT
  web:
    container_name: web
    image: web
    depends_on:
      - bot
      - postgres
    build:
      context: ../web-control
      dockerfile: Dockerfile
    environment:
      - GO_BOT_URL=http://bot:5504
    ports:
      - 80:3000

volumes:
  postgres: null
